# Markdownlint Configuration
# This file configures markdownlint rules for consistent Markdown formatting
# For all available rules: https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md

# MD013 - Line length limit
# Enforces a maximum line length for readability, but excludes certain content types
# that naturally have longer lines or where wrapping would break functionality
# Documentation: https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md013---line-length
MD013:
  code_blocks: false # Don't enforce line length in code blocks (preserves code formatting)
  tables: false # Don't enforce line length in tables (prevents table structure breakage)
