name: 'My Broken Link Checker'
description: 'Broken link checker for web pages located localy or remotely'
author: 'ruzickap'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'list'
  color: 'blue'
inputs:
  debug:
    description: 'Debug mode'
  cmd_params:
    description: 'Command line parameters for URL checker'
  pages_path:
    description: 'Relative path to the directory with local web pages'
  run_timeout:
    description: 'Maximum number of seconds that URL checker can be running'
    default: '300'
  url:
    description: 'URL which will be checked'
    required: true
    default: ''
