name: tests

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - tests/**
      - .github/workflows/tests.yml
      - entrypoint.sh
      - Dockerfile
      - .dockerignore
  push:
    branches:
      - main
    paths:
      - tests/**
      - .github/workflows/tests.yml
      - entrypoint.sh
      - Dockerfile
      - .dockerignore

permissions:
  contents: read

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run tests
        run: ./run_tests.sh
        working-directory: ./tests/
