name: update-semver

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Semver
        uses: haya14busa/action-update-semver@v1
        with:
          major_version_tag_only: true
          github_token: ${{ secrets.github_token }}
